# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99892e37df282e1a107d05f29722d8582a01b51ad247e3191d8b6902e574122734e89f1e16f74739d91cfbaa62fa8cafaa942ed3aceeba2904ba69a719265d5f

test:
  secret_key_base: 7260f7093b874591514aeea288a2bad1504dc8129cf2a4fd0039230ccb503d088cff230d045fce84d0a940c7e6890e4447b03f73a6c377faf8775707be3fd6c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
